### ISSUE TITLE
Fails to build on MacOS

### ISSUE THREAD

**Issue by ep1cman** [pengutronix/microcom#59]
When trying to compile on MacOS I get the following error:

```
/Library/Developer/CommandLineTools/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT microcom.o -MD -MP -MF .deps/microcom.Tpo -c -o microcom.o microcom.c
microcom.c:49:5: error: use of undeclared identifier 'IUCLC'
   49 |                          IUCLC | IXANY | IMAXBEL);
      |                          ^
microcom.c:50:35: error: use of undeclared identifier 'XCASE'
   50 |         sts.c_lflag &= ~(ICANON | ISIG | XCASE);
      |                                          ^
2 errors generated.
make[1]: *** [microcom.o] Error 1
make: *** [all] Error 2
```

Looks like this was caused by 96e00523201503bf022cb8b990948708475bc631. Prior to this commit it builds successfully and seems to work as expected.

**Comment by jonrebm** [comment]
Merged https://github.com/pengutronix/microcom/pull/60
